version: '3'

services:
  orders:
    container_name: orders_database
    image: postgres:15.3-alpine
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=orders_db